import re

import bcrypt

from utils.database import (
    create_user,
    load_user,
    mark_onboarding_complete,
    save_personalization_profile,
    user_exists,
)


USERNAME_PATTERN = re.compile(r"^[a-zA-Z0-9_.-]{3,30}$")


def _validate_username(username: str) -> str | None:
    if not username:
        return "Username cannot be empty."

    if not USERNAME_PATTERN.fullmatch(username):
        return (
            "Username must be 3–30 characters and may use only "
            "letters, numbers, dots, hyphens, and underscores."
        )

    return None


def _validate_password(password: str) -> str | None:
    if not password:
        return "Password cannot be empty."

    if len(password) < 8:
        return "Password must be at least 8 characters."

    if len(password) > 128:
        return "Password is too long."

    return None


def web_login(username: str, password: str) -> dict:
    """
    Authenticate an existing user.

    Returns safe user data only. password_hash never leaves this service.
    """

    username = username.strip()

    username_error = _validate_username(username)

    if username_error:
        return {
            "status": "error",
            "message": username_error,
        }

    password_error = _validate_password(password)

    if password_error:
        return {
            "status": "error",
            "message": password_error,
        }

    user = load_user(username)

    if user is None:
        return {
            "status": "error",
            "message": "Invalid username or password.",
        }

    password_hash = user["password_hash"]

    if not password_hash:
        return {
            "status": "error",
            "message": (
                "This account was created before password login was added. "
                "Create a new account to continue."
            ),
        }

    password_matches = bcrypt.checkpw(
        password.encode("utf-8"),
        password_hash.encode("utf-8"),
    )

    if not password_matches:
        return {
            "status": "error",
            "message": "Invalid username or password.",
        }

    return {
        "status": "success",
        "user_id": user["id"],
        "username": user["username"],
        "name": user["name"],
        "onboarding_complete": bool(user["onboarding_complete"]),
    }


def web_signup(username: str, name: str, password: str) -> dict:
    """
    Create a new Novateach account.
    """

    username = username.strip()
    name = name.strip()

    username_error = _validate_username(username)

    if username_error:
        return {
            "status": "error",
            "message": username_error,
        }

    if not name:
        return {
            "status": "error",
            "message": "Name cannot be empty.",
        }

    if len(name) > 100:
        return {
            "status": "error",
            "message": "Name must be at most 100 characters.",
        }

    password_error = _validate_password(password)

    if password_error:
        return {
            "status": "error",
            "message": password_error,
        }

    if user_exists(username):
        return {
            "status": "error",
            "message": "An account with this username already exists.",
        }

    password_hash = bcrypt.hashpw(
        password.encode("utf-8"),
        bcrypt.gensalt(),
    ).decode("utf-8")

    user_id = create_user(
        username=username,
        name=name,
        password_hash=password_hash,
    )

    return {
        "status": "success",
        "user_id": user_id,
        "username": username,
        "name": name,
        "onboarding_complete": False,
    }


def save_web_personalization(
    username: str,
    answers: dict,
    extra_learning_info: str,
) -> dict:
    """
    Save user-provided onboarding preferences.

    These are 'You told us' signals, separate from evidence-based
    learner model data that will be generated by quizzes later.
    """

    username = username.strip()
    extra_learning_info = extra_learning_info.strip()

    if not user_exists(username):
        return {
            "status": "error",
            "message": "User account was not found.",
        }

    if not isinstance(answers, dict):
        return {
            "status": "error",
            "message": "Personalization answers must be an object.",
        }

    required_keys = {
        "understanding_strategy",
        "support_strategy",
        "difficulty_trigger",
        "teaching_strategy",
        "retention_pattern",
        "pace_preference",
    }

    missing_keys = sorted(
        key
        for key in required_keys
        if not answers.get(key)
    )

    if missing_keys:
        return {
            "status": "error",
            "message": "Please answer every personalization question.",
        }

    save_personalization_profile(
        username=username,
        answers=answers,
        extra_learning_info=extra_learning_info,
    )

    mark_onboarding_complete(username)

    return {
        "status": "success",
        "message": "Your learning preferences were saved.",
    }